### ISSUE TITLE
Value of InputColumn is blank in export

### ISSUE THREAD

**Issue by almirb** [yiister/yii2-advanced-grid#3]
Hi!

I'm using your InputColumn and noticed the value is blank when generating html/pdf/excel...
Could you fix It?

*If I find the solution, will make a PR.

**Comment by algushchin** [comment]
Hello!
Could you tell me more information about this problem? What tool do you use for a generation html/pdf/excel?

**Comment by almirb** [comment]
Sorry about not mentioning before, but I use [Kartik Gridview export](http://demos.krajee.com/grid#grid-export).  I could overcome this problem using one column for Input (visible and export-disabled) and another only with the value (hidden, but exportable).

The only remaining issue: I need to refresh the grid before exporting to update all the changed values.

Thanks for your attention!

**Comment by fps01** [comment]
Hello!
It's no best way to fix problem. I think we can add some styles for column but I need test it with kartik gridview first.

**Comment by almirb** [comment]
I'll close this thread because this shouldn't considered an "issue".

Thank you for sharing this components with the Yii Community. :)
